### ISSUE TITLE
In the wait for linux support, is there a workaround?

### ISSUE THREAD

**Issue by MikeCroall** [bitgamma/updatefx#1]
Can we somehow pretend that our linux OS is windows or mac? We're distributing the same .jar for all platforms so it shouldn't matter... Can we somehow ignore platform entirely?

Many thanks!

**Comment by bitgamma** [comment]
Currently, there is no workaround. Linux is a "difficult" architecture, because we would need to detect if we run on a RPM-based or DEB-based distro (remember, UpdateFX is mainly thought for updating applications packaged using javafxpackager, where the platform is relevant). However, I would gladly accept a PR for supporting "platform independent" updates which can be used in case of jar-only distributions.

**Comment by MikeCroall** [comment]
Pull request has been sent. Independent updates have been tested to work for windows (x64) and linux (ubuntu 16.04), but have been having problems with mac, and I am unsure why as I haven't changed anything to do with mac specifically. Was this already an issue?

**Comment by bitgamma** [comment]
Closed by #2
